apps/core/urls.py
from django.urls import path

from .views import (
    home_view,
    generate_key_view,
    encryptDecryptView,
    EncryptDecryptView
)



app_name = 'core'

urlpatterns = [
    path('', home_view, name='home'),
    path('update-key/<int:id>/', home_view, name='home'),
    path('generate/key/', generate_key_view, name='generate_key'),
    path('encrypt-decrypt/', EncryptDecryptView.as_view(), name='encrypt_decrypt'),
]

proroot/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    # django-tinymce-lite4 url route
    path('tinymce/', include('tinymce.urls')),
    # django-smart-select url route
    path('chaining/', include('smart_selects.urls')),
    
    # rest_framework api url route for login and logout
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
    path('', include('apps.core.urls', namespace='core')),
    path('users/', include('apps.users.urls', namespace='user'))
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

templates/crytokey.html
{% extends 'index.html' %}

{% block body %}
    
    {% comment %} {% if key_info.name %}
        <h1>{{ key_info.name }}</h1>
    {% else %}
        <h1>Asymmetric Cryptography</h1>
    {% endif %} {% endcomment %}


    <div class="container-fluid py-2">
        
            <div class="form-row">
                <div class="col-9">
                    <fieldset>
                        <legend>Input text</legend>
                        <div class="form-row">
                            <div class="col-12" style="margin-top:30px">
                                <fieldset>
                                    <legend>Generate</legend>
                                    <div class=" form-row" style="margin-top:30px">
                                        {% if key_info %}
                                        <div class="form-group col-6 generated-keys">
                                            <textarea class="form-control small" rows="18" name="" id="" placeholder="private key..." readonly>{{ key_info.private_key|safe }}</textarea>
                                        </div>
                                        <div class="form-group col-6">
                                            <textarea class="form-control small" rows="18" name="" id="" placeholder="public key..." readonly>{{ key_info.public_key|safe }}</textarea>
                                        </div>
                                        {% else %}
                                        <div class="form-group col-6 generated-keys">
                                            <textarea class="form-control small" rows="18" name="" id="" placeholder="private key..." readonly></textarea>
                                        </div>
                                        <div class="form-group col-6">
                                            <textarea class="form-control small" rows="18" name="" id="" placeholder="public key..." readonly></textarea>
                                        </div>
                                        {% endif %}
                                        <div class="col-12">
                                            <form method='post' class='w-100 d-flex' action='{% url "core:generate_key" %}'>
                                                {% csrf_token %}
                                                {{ form.non_field_errors }}
                                                
                                                <input type="text" name='name' id='name' class="form-control mr-3" placeholder='Key name ...' required>
                                                <button class="btn btn-sm" style="background-color: #9DAAF2; color:#fff;" type="submit">Generate</button>
                                            </form>                                            
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-3">
                    <fieldset class="h-100">
                        <legend>Save Generate</legend>
                        <div class="form-row">
                            <div class="col-12" style="margin-top:30px">
                                <div class="p-3">
                                    <h4>Save Generate</h4>
                                    <div class="">
                                        <ul class="unstyled">
                                            {% for key in key_queryset %}
                                            <li>
                                                <div>
                                                    <a href='{% url "core:home" key.id %}'>{{ key.name }}</a> 
                                                    {% if key.private_key_file %}
                                                        <a href='{{ key.publicKeyUrl }}'>download private key</a>
                                                    {% endif %}
                                                    {% if key.public_key_file %}
                                                        <a href='{{ key.privateKeyUrl }}'>download public key</a>
                                                    {% endif %}
                                                    <p>{{ key.updated_at|date:'D d M Y' }}</p>
                                                </div>
                                            </li>
                                        {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        
    </div>















    
    

    
    <a href="{% url 'core:encrypt_decrypt' %}">encrypt/decrypt</a>
       
{% endblock  %}

templates/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
     <style>
        body{
            background-color: lightgray;
         }
        fieldset {
            font-size: 14px;
            background-color: white;
            border: solid thin #aaaaaa;
            box-sizing: border-box;
            border-radius: 5px;
            padding: 0.5rem;
            box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
            position: relative;
        }
        
        fieldset legend {
            top: 0;
            left: 0;
            position: absolute;
            font-size: 12px;
            box-sizing: border-box;
            border: none;
            background-color: #9DAAF2;
            border-radius: 4px 4px 0 0;
            color: white;
            padding: 0.3rem 0.5rem;
        }
        
        .ul li {
            display: inline-block;
        }
     </style>
    <body>

        {% include 'includes/header.html' %}

        {% block body %}
        
        {% endblock  %}
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="" async defer></script>
    </body>
</html>

templates/message.html
{% extends 'index.html' %}


{% block body %}
    <div class="container-fluid py-2"  style="background-color: lightgray;">

        <form action="" class="" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-row">
                <div class="col-12 col-sm-12 col-md-7">
                    <fieldset>
                        <legend>Input text</legend>
                        <div class="form-row">
                            <div class="col-12" style="margin-top:30px">
                                <fieldset>
                                    <legend>Generate</legend>
                                    <div class=" form-row" style="margin-top:30px">
                                        <div class="form-group col-12">
                                            {{ form.private_key }}
                                             {{ form.private_key.errors }}
                                         
                                        </div>
                                        <div class="form-group col-12">
                                            {{ form.public_key }}
                                             {{ form.public_key.errors }}
                                        </div>

                                    </div>
                                </fieldset>
                            </div>
                        </div>

                        <div class="row" style="margin-top:20px">
                            <div class="col-12">
                                <fieldset>
                                    <legend>My text</legend>
                                    <div class="form-row" style="margin-top:30px">
                                        <div class="form-group col-12 col-sm-9 col-md-9 col-lg-10">
                                            {{ form.message }}
                                            {{ form.message.error }}
                                        </div>
                                        <div class="form-group col-12 col-sm-3 col-md-3 col-lg-2">
                                            <div class="d-flex flex-column justify-content-end .justify-content-md-center">
                                                <button class="btn btn-sm" style="background-color: #9DAAF2; color:#fff;" type="submit">Enc/Dec</button>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                    </fieldset>
                </div>

                <div class="col-12 col-sm-12 col-md-5 mt-2 mt-md-0">
                    <fieldset class="h-100">
                        <legend>Output text</legend>
                        <div class="row" style="margin-top:30px">
                            <div class="form-group col-12">
                                <textarea class="form-control" name="result_text" id="result_text" cols="30" rows="21" 
                                    placeholder="The results will be displayed here." readonly>{{ result_message }}</textarea>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>

    <br>
    <br>
    <br>
    <br>

    <div> 
        {% if errors %}
            {% for error in errors %}
                {% if error %}:
                    <p>{{ error }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <br>
    <br>
    <br>
    <br>


    <a href="{% url 'core:home' %}">home</a>



{% endblock  %}